//
// Created by bingy on 2021/3/13.
//

#ifndef INC_011_FFMPEG_MASTER_DZCONSTDEFINE_H
#define INC_011_FFMPEG_MASTER_DZCONSTDEFINE_H

#include <android/log.h>
#define TAG "JNI_TAG"
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, TAG, __VA_ARGS__)

#define AUDIO_SAMPLE_RATE 44100
#endif //INC_011_FFMPEG_MASTER_DZCONSTDEFINE_H

#define FIND_STREAM_ERROR_CODE -0x10
#define FIND_STREAM_INFO_ERROR_CODE -0x11
#define FIND_BEST_STREAM_ERROR_CODE -0x12
#define CODED_FIND_DECODER_ERROR_CODE -0x13
#define ALLOCATE_CONTEXT_ERROR_CODE -0x14
#define AVCODEC_PARAM_TO_CONTEXT_ERROR_CODE -0x15
#define AVCODEC_OPEN_2_ERROR_CODE -0x16